num1 = input('[Enter first number: ')
num2 = input('Enter second number: ')
sum = int(num1) + int(num2)
sub = int(num1) - int(num2)
mul = int(num1) * int(num2)
div = int(num1) / int(num2)
print(sum)
print(sub)
print(mul)
print(div)
